import Head from 'next/head'

import Header from '../components/Header';
import Post from '../components/Post';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<Header />

			<main>
				<div className='py-4 min-h-screen space-y-4'>
					<Post />
					<Post />
				</div>
			</main>
		</>
	)
}
