import prisma from '../lib/prisma';

import Head from 'next/head'

import Header from '../components/Header';
import Post from '../components/Post';

export default function Home({ posts }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<Header />

			<main>
				<div className='py-4 min-h-screen space-y-4'>

					{posts && posts.map(post => (
						<Post key={post.id} post={post} />
					))}

				</div>
			</main>
		</>
	)
}

export async function getStaticProps() {

	const posts = await prisma.post.findMany()

	return {
		props: { posts }
	}
}
